### ISSUE TITLE
Getting dockcer ip insted of users ubuntu server 

### ISSUE THREAD

**Issue by cryptoruby** [openware/opendax#117]
Hi, I am getting docker container private IP, How can I fix it?
https://i.imgur.com/OF01FZo.jpg

**Comment by lekabyte** [comment]
i have the same problem. did you solve it?

**Comment by ruby261** [comment]
nop was I asked multiple times but no one seems to help.
Someone said an upgrade to the new version will solve it but did not work for me.

**Comment by lekabyte** [comment]
Here are my findings

docker container ip is detected up to barong 2.3.46. in 2.3.47 detects real client ip but websocket stops to work.

the diff between barong to detect real client ip is in file
"lib\barong\cloudflare_middleware.rb"

in 2.3.46: "ips = ips_from('HTTP_X_FORWARDED_FOR')"
in 2.3.47: "ips = ips_from(@env['HTTP_X_FORWARDED_FOR'])"

if you change this it will detect real client ip. but i can't get websocket to work. i get described here: https://github.com/openware/opendax/issues/132

tried also without using cloudflare service.

**Comment by ruby261** [comment]
@lekabyte  did you change to code ?

**Comment by ruby261** [comment]
I am using 2.3.47 and I am getting cloudflare IP not users ip

**Comment by lekabyte** [comment]
i was using cloudflare too. but never got cloudflare ip. i got docker container ip instead. i got it fixed. don't have the best solution, but it works. i will post when i get back home what versions i am using and what i changed

**Comment by ruby261** [comment]
@lekabyte thank you for your reply. 
At first, I was getting docker. I made the changes after seeing your comment and now I am getting Cloudflare IP, I will wait for your post.

**Comment by ruby261** [comment]
peatio: quay.io/openware/peatio:2.3.55
  barong: quay.io/openware/barong:2.3.48

fixed it for me.

**Comment by dpatsora** [comment]
Hello 
We are so sorry that we reply to you so late. 
We fixed this issue in quay.io/openware/barong:2.3.48.

Sincerely yours,
Openware Team
