### ISSUE TITLE
Tag 2.2.23 was deleted or has expired. To pull, revive via time machine rake aborted!

### ISSUE THREAD

**Issue by xbhuang1994** [openware/opendax#13]
Pulling frontend (quay.io/openware/baseapp-lite:2.2.23)...
ERROR: unknown: Tag 2.2.23 was deleted or has expired. To pull, revive via time machine
rake aborted!
Command failed with status (1): [docker-compose up -d frontend...]
lib/tasks/service.rake:145:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:153:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:236:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:253:in `block (2 levels) in <top (required)>'
Tasks: TOP => service:frontend
(See full trace by running task with --trace)

**Comment by bzero** [comment]
on your config/app.yml change the line:

-  frontend: quay.io/openware/baseapp-lite:2.2.23  # Check on quay.io/openware for latest tags
+  frontend: quay.io/openware/baseapp-lite:2.2.34  # Check on quay.io/openware for latest tags
