### ISSUE TITLE
Parity Setup up

### ISSUE THREAD

**Issue by cleardex** [openware/opendax#131]
Hello, I noticed the testnet or Kovan loads instantly (a few seconds with the following setup) in compose/cryptonodes.yaml

  parity:
    image: parity/parity:v2.5.13-stable
    restart: always
    command: |
      --chain=kovan
      --mode=active
      --interface=all
      --warp=true
      --snapshot-peers=10
      --min-peers=5
      --max-peers=10
      --jsonrpc-interface=0.0.0.0
      --jsonrpc-cors=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=all
      --db-compaction=ssd
    volumes:
      - ../data/parity:/home/parity/.local/share/io.parity.ethereum
    ports:
      - "127.0.0.1:8545:8545"

However, changing to mainnet stays on Block 0 height forever

  parity:
    image: parity/parity:v2.5.13-stable
    restart: always
    command: |
      --chain=mainnet
      --mode=active
      --interface=all
      --warp=true
      --snapshot-peers=10
      --min-peers=5
      --max-peers=10
      --jsonrpc-interface=0.0.0.0
      --jsonrpc-cors=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=all
      --db-compaction=ssd
    volumes:
      - ../data/parity:/home/parity/.local/share/io.parity.ethereum
    ports:
      - "127.0.0.1:8545:8545"

Is there a bug in your system?

**Comment by Shreybhardwaj97** [comment]
Hi I've same question on this one.  I was trying to add new cryptocurrency and started with the Bitcoin network.  But configuration is not available. Is there any Document which we can follow and make it running for other currencies as well?

**Comment by mikoim** [comment]
@Shreybhardwaj97 Refer to these templates. You should create a new entry at blockchain, currency, and wallets.
https://github.com/openware/opendax/tree/2-3-stable/templates/config/peatio/seed

**Comment by Shreybhardwaj97** [comment]
@mikoim Thank you for your support on this.  If you can provide any document on using and setting up these crypto nodes it will be really helpful for us.

**Comment by Shreybhardwaj97** [comment]
@mikoim Thank-you very much for your help .  I have one question is necessary to run the peatio locally and then configure it in App.yml or the quay.io image will also work fine for the new crypt-currencies? 

Because I tried to set up the currencies it is not supporting the configuration.

**Comment by Shreybhardwaj97** [comment]
Hi I'm getting an error when ssh to  docker-compose exec peatio bash

curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"personal_newAccount","params":["passphrase"],"id":42}' parity:8545

curl: (6) Could not resolve host: parity

**Comment by lekabyte** [comment]
when i start docker container i get error...

```
parity_1                   | Option '--warp' does nothing. It's on by default.
parity_1                   | Error upgrading parity data: CannotCreateConfigPath(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
parity_1                   | Option '--warp' does nothing. It's on by default.
parity_1                   | Error upgrading parity data: CannotCreateConfigPath(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
parity_1                   | Option '--warp' does nothing. It's on by default.
parity_1                   | Error upgrading parity data: CannotCreateConfigPath(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
```

also looks like --warp version is is enough. is it mendatory to use full node?

**Comment by eliudrojas** [comment]
Somebody could help me with this error:

parity_1                   | Option '--warp' does nothing. It's on by default.
parity_1                   | Error upgrading parity data: CannotCreateConfigPath(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })

**Comment by ThemeMetro** [comment]
> Somebody could help me with this error:
> 
> parity_1 | Option '--warp' does nothing. It's on by default. parity_1 | Error upgrading parity data: CannotCreateConfigPath(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })

did you able to fix?
