### ISSUE TITLE
deposits not working at all

### ISSUE THREAD

**Issue by lekabyte** [openware/opendax#144]
can't get deposits to work. i tried litecoin testnet.
build daemon from source (version 0.15.1 - last verified that allows ./litecoin-cli getinfo)

edit litecoin.conf file:
```
printtoconsole=1
daemon=1
server=1
txindex=1
rpcallowip=MY LOCAL IP
rpcallowip=MYEXTERNAL SERVER IP
rpcbind=0.0.0.0
rpcport=19335
port=19332
rpcpassword=mypassword
rpcuser=myuser
testnet=1
```
i got full sync.

edited litecoin blockchain in tower:
```
name: ltc-blockchain
client: litecoin
server: http://mypassword:myuser@MYEXTERNALIPWHEREIRUNDAEMON:19335
key: ltc-blockhain
height: 1465713
min confirmations: 6
```

added wallets (tower/settings/wallets):
deposit, fee, hot, warm, cold

```
uri: http://mypassword:myuser@MYEXTERNALIPWHEREIRUNDAEMON:19335
sercret: empty/none
currency id: ltc
gateway: litecoind
blockchain key: ltc-blockhain
```

for deposit:
```
- max balance: 50,0 (others higher 10-1000)
- generated address ./litecoin-cli getnewadress so every wallet (fee, deposit, hot, warm, etc) have it's own.
```

created currency (tower/exchange/currencies):
```
name: Litecoin
code: ltc
symbol: L
type: coin
subunits: 8
precision: 8
deposit fee: 0
min deposit amount: 0,01
min colleciton amount: 0,0
min withdraw fee: 0,01
min widraw amount: 0,1
24h limit: 99999999999,0
72h limit: 99999999999,0
position: 0
icon url: https://s2.coinmarketcap.com/static/img/coins/64x64/2.png
```

address for deposit generated without problem.
used https://faucet.xblau.com/ to send 0.1 ltc to address that generated for me.
waited 6 confirmations.
transaction is seen on testnet explorer
also ./litecoin-cli getbalance gives me correct balance of 0.1 ltc
opendax never register any deposit in history.

so my question is do you need to put something like walletnotify= in litecoin.conf file for opendax to receive information about new transaction? or how do you get deposits to work. also if there is any withdrawal issue or special setup needed i would be happy you could tell me about it.

**Comment by lekabyte** [comment]
same thing with bitcoin testnet v0.19.1

widrawal work half way
`mjFBdzsYNBCeabLNwyYYCt8epG7GhzYeTw 08-05-2020 21:10:37	LTC	0.10000000 0.01 Confirming`

stuck on confriming even there are more then 6 confirmations.

**Comment by SimonHausdorf** [comment]
what about container logs?

**Comment by lekabyte** [comment]
i checked all logs. nothing shows up. do you want me to check any specific log?

deposit_collection? deposit_collection_fees? withdraw_audit? withdraw_coin?

can't find anything special...

**Comment by SimonHausdorf** [comment]
can you try `docker logs --tail=50 bitsiam_blockchain_1` if there is anything?
Also after adding the blockchain, did you restart the service? `rake service:daemons[restart]`

**Comment by SimonHausdorf** [comment]
also make sure that deposit is > `min deposit amount: 0,01`, you can also set it to 0

**Comment by lekabyte** [comment]
i am not running daemons on same server.

**Comment by lekabyte** [comment]
```
{"level":"WARN","time":"2020-05-09 19:28:02","message":"Error: Failed to open TCP connection to :80 (Cannot assign requested address - connect(2) for nil port 80). Sleeping for 10 seconds"}
{"level":"ERROR","time":"2020-05-09 19:28:08","message":"#<Peatio::Blockchain::ClientError: Failed to open TCP connection to parity:8545 (getaddrinfo: Name or service not known)>"}
{"level":"ERROR","time":"2020-05-09 19:28:08","message":"/home/app/lib/peatio/ethereum/blockchain.rb:60:in `rescue in latest_block_number'\n/home/app/lib/peatio/ethereum/blockchain.rb:57:in `latest_block_number'\n/home/app/app/services/blockchain_service.rb:16:in `latest_block_number'\n/home/app/app/workers/daemons/blockchain.rb:22:in `process'\n/home/app/app/workers/daemons/blockchain.rb:9:in `block (2 levels) in run'"}
{"level":"WARN","time":"2020-05-09 19:28:08","message":"Error: Failed to open TCP connection to parity:8545 (getaddrinfo: Name or service not known). Sleeping for 10 seconds"}
{"level":"ERROR","time":"2020-05-09 19:28:12","message":"#<Peatio::Blockchain::ClientError: Failed to open TCP connection to :80 (Cannot assign requested address - connect(2) for nil port 80)>"}
{"level":"ERROR","time":"2020-05-09 19:28:12","message":"/opt/vendor/bundle/ruby/2.6.0/gems/peatio-dash-0.1.2/lib/peatio/dash/blockchain.rb:39:in `rescue in latest_block_number'\n/opt/vendor/bundle/ruby/2.6.0/gems/peatio-dash-0.1.2/lib/peatio/dash/blockchain.rb:36:in `latest_block_number'\n/home/app/app/services/blockchain_service.rb:16:in `latest_block_number'\n/home/app/app/workers/daemons/blockchain.rb:22:in `process'\n/home/app/app/workers/daemons/blockchain.rb:9:in `block (2 levels) in run'"}
{"level":"WARN","time":"2020-05-09 19:28:12","message":"Error: Failed to open TCP connection to :80 (Cannot assign requested address - connect(2) for nil port 80). Sleeping for 10 seconds"}
```

repeating. but i have eth disabled. i am using only bitcoin and litecoin both on testnet

**Comment by SimonHausdorf** [comment]
and you are sure you restarted the blockchain daemon? It could be that ethereum processing is blocking the other executions but I am not sure.

**Comment by lekabyte** [comment]
yes i restarted. did it just now once again.
same output. it must be ethereum. still trying to connecto to parity:8545

how do i disable this?

**Comment by SimonHausdorf** [comment]
seems like the disable button does not have any effect. You could delete the blockchain from the database ...

You could access the rails console and check with `Blockchain.all` which one to delete. Then check again after restart. It seems like that this is causing the issue.

**Comment by lekabyte** [comment]
deleted all unused blockchains,currencies,markets from database. and it worked! it does work not. perfect!

**Comment by lekabyte** [comment]
if i may ask you one more thing about ethereum with parity. what node size is required? do i need full node? it's a lot of data so sync. it's ok if you sync smaller? like normal or warp?

**Comment by SimonHausdorf** [comment]
I am not sure to be honest. I tried once to connect a geth light node but it didn't work as one api command wasn't available and I think it only works with full node. Not sure about the size but it's a lot, yes ...

**Comment by lekabyte** [comment]
ok. will try full node then. got 2tb ssd comming on thursday. for all others who also going to read this. don't bother using anything else but ssd for eth sync. there was wallet attack and it's a lot of useless blocks.
