### ISSUE TITLE
Installer File not working

### ISSUE THREAD

**Issue by fullmad** [openware/opendax#154]
curl: (22) The requested URL returned error: 404 Not Found

**Comment by lackorol** [comment]
The same 404

**Comment by dpatsora** [comment]
Hello!
Would you be kind enough to provide us more description about the issue?
On which request you've got this error?

**Comment by fullmad** [comment]
Thank you for your reply and appreciate your hard work on this project. I am referring to this:
 ruby -e "$(curl -fsSL https://raw.githubusercontent.com/openware/opendax/master/bin/install)"

**Comment by lackorol** [comment]
May I ask you about opendax? I have deployed everything rake services:all
and have blank template page. Is required to set up ssl certificate?
Because domain was.

Bc Ladislav Rolnik CGI

**Comment by dpatsora** [comment]
Hello!
Please, clone Opendax and run:
1. `chmod +x bin/install.sh`
2. `bin/install.sh`
3. Install RVM
4. Restart the machine to apply docker changes
5. `bundle install`
6. Fill `config/app.yml`
6. `rake service:all`

If you don't have domain - you can run it locally and access the platform using www.app.local
Read about it in our README( section 4)

Sincerely yours,
Openware Team

**Comment by dpatsora** [comment]
Setting up ssl is not required.
In `config/app.yml` in `ssl` section just set `enabled` to `false`

**Comment by lackorol** [comment]
I got blue screen with no forms.
www.coincoin.biz please check
all services are running with minimal
changes in app.yml

Bc Ladislav Rolnik CGI

**Comment by dpatsora** [comment]
Would you be kind enough to send us screenshot with output of `docker-compose ps` and content of `config/app.yml`

Sincerely yours,
Openware Team

**Comment by lackorol** [comment]
Here are screenshots of docker ps and app.yaml.Thank you for support Sent from Mail for Windows 10 From: dpatsoraSent: Monday, June 1, 2020 1:58 PMTo: openware/opendaxCc: lackorol; CommentSubject: Re: [openware/opendax] Installer File not working (#154) Would you be kind enough to send us screenshot with output of docker-compose ps and content of config/app.ymlSincerely yours,Openware Team—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by UbuntuEvangelist** [comment]
@dpatsora I am using Ubuntu 19.04 LTS 

app@vmi387949:~/opendax$ sudo docker-compose ps
Name   Command   State   Ports
------------------------------
app@vmi387949:~/opendax$ cat config/app.yml
---
app:
  name: OpenDAX
  domain: ardax.com.ar
  subdomain: www
render_protect: false
csrfEnabled: false
ssl:
  enabled: false
  email: support@ardax.com.ar
images:
  peatio: quay.io/openware/peatio:latest
  barong: quay.io/openware/barong:2.4.1
  frontend: quay.io/openware/baseapp:latest
  tower: quay.io/openware/tower:2.4.5
finex:
  enabled: false
  image: quay.io/openware/finex:2.4.0-5334683
vendor:
  frontend: git@github.com:openware/baseapp.git
vault:
  token: 
database:
  host: db
  port: 3306
  user: root
  password: changeme
storage:
  provider: Google
  bucketName: opendax-barong-docs-bucket
  region: fra1
  endpoint: https://fra1.digitaloceanspaces.com
  accessKey: changeme
  secretKey: changeme
  signatureVersion: '2'
twilio:
  enabled: false
  phone_number: "+15005550000"
  account_sid: changeme
  auth_token: changeme
gaTrackerKey: ''
captcha:
  type: none
  siteKey: changeme
  secretKey: changeme
smtp:
  host: smtp.sendgrid.net
  port: 2525
  user: apikey
  password: changeme
  sender_email: noreply@barong.io
  sender_name: Postmaster
wallets:
  eth:
  - kind: deposit
    address: changeme
    max_balance: 0.0
    secret: changeme
  - kind: hot
    address: changeme
    max_balance: 100.0
    secret: changeme
  - kind: warm
    address: changeme
    max_balance: 1000.0
    secret: changeme
  btc:
  - kind: deposit
    address: changeme
    max_balance: 0.0
  - kind: hot
    address: changeme
    max_balance: 100.0
  - kind: warm
    address: changeme
    max_balance: 1000.0
parity:
  network: testnet
  address: parity
  rpcport: 8545
  port: 30303
bitcoind:
  enabled: false
  rpcuser: admin
  rpcpassword: changeme
  address: bitcoind
  network: testnet
  rpcport: 18332
  port: 18333
litecoind:
  rpcuser: admin
  rpcpassword: changeme
  address: litecoind
  network: testnet
  rpcport: 19332
  port: 19335
terraform:
  credentials: "~/safe/opendax.json"
  project: example-opendax
  region: europe-west4
  zone: europe-west4-a
  instance_name: opendax-cloud
  machine_type: n1-standard-4
  image: debian-cloud/debian-9

**Comment by dpatsora** [comment]
Hello!
It looks like none of the containers run.
Did you run `rake service:all`?

Sincerely yours,
Openware Team

**Comment by UbuntuEvangelist** [comment]
@dpatsora yes I did run rake service:all
![Screenshot from 2020-06-02 03-02-39](https://user-images.githubusercontent.com/1058663/83454210-aedfef00-a47d-11ea-8a8d-0b8e29d2acd9.png)


app@vmi387949:~/opendax$ rake service:all
Rendering ./config/peatio.env
Rendering ./config/applogic.env
Rendering ./config/mailer.yml
Rendering ./config/finex/config.yaml
Rendering ./config/finex/rsa-key.pub
Rendering ./config/litecoin.conf
Rendering ./config/frontend/tower.js
Rendering ./config/frontend/env.js
Rendering ./config/mysql/innodb.cnf
Rendering ./config/bitcoin.conf
Rendering ./config/toolbox.yaml
Rendering ./config/peatio/management_api_v1.yml
Rendering ./config/peatio/seed/trading_fees.yml
Rendering ./config/peatio/seed/markets.yml
Rendering ./config/peatio/seed/blockchains.yml
Rendering ./config/peatio/seed/wallets.yml
Rendering ./config/peatio/seed/accounts.yml
Rendering ./config/peatio/seed/currencies.yml
Rendering ./config/barong/management_api.yml
Rendering ./config/barong/seeds.yml
Rendering ./config/barong.env
Rendering ./config/arke.env
Rendering ./config/applogic/schedule.yml
Rendering ./config/applogic/management_api_v2.yml
Rendering ./config/gateway/envoy.yaml
Rendering ./config/ranger.env
Rendering ./config/arke/strategies.yml
Rendering ./terraform/terraform.tfvars
Rendering ./.env
Rendering ./compose/monitoring.yaml
Rendering ./compose/cryptonodes.yaml
Rendering ./compose/app.yaml
Rendering ./compose/superset.yaml
Rendering ./compose/frontend.yaml
Rendering ./compose/gateway.yaml
Rendering ./compose/daemons.yaml
Rendering ./compose/backend.yaml
Rendering ./compose/arke.yaml
Rendering ./compose/vendor.yaml
Rendering ./compose/proxy.yaml
----- Starting the proxy -----
docker-compose up -d proxy
Creating network "opendax_default" with the default driver
Creating opendax_proxy_1 ... done
----- Starting dependencies -----
docker-compose up -d vault db redis rabbitmq
Creating opendax_db_1       ... done
Creating opendax_redis_1    ... done
Creating opendax_rabbitmq_1 ... done
Creating opendax_vault_1    ... done
----- Starting influxdb -----
docker-compose up -d influxdb
Creating opendax_influxdb_1 ... done
docker-compose exec influxdb bash -c "cat peatio.sql | influx"
Failed to connect to http://localhost:8086: Get http://localhost:8086/ping: dial tcp 127.0.0.1:8086: connect: connection refused
Please check your connection settings and ensure 'influxd' is running.
rake aborted!
Command failed with status (1): [docker-compose exec influxdb bash -c "cat ...]
lib/tasks/service.rake:62:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:70:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:279:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:302:in `block (2 levels) in <top (required)>'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/app/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/home/app/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => service:influxdb
(See full trace by running task with --trace)

**Comment by lackorol** [comment]
Something misconfigured in attached screenshots?

**Comment by freakcoderz** [comment]
Shows rake aborted due to not being able to connect to port 8086.

**Comment by lackorol** [comment]
I have 
Can't connect to MySQL server on 'db' (115)
Couldn't create 'barong_production' database. Please check your configuration.
rake aborted!

**Comment by lackorol** [comment]
I have
Can't connect to MySQL server on 'db' (115)
Couldn't create 'peatio_production' database. Please check your configuration.
rake aborted!

**Comment by lackorol** [comment]
I have this error by first time launching rake service:all,
on next attempt it successfully finished but my app is blank page.

**Comment by freakcoderz** [comment]
I have the same blank page issue on the site. The browser console stats it is missing data so must be something missing in the app.yml I didn't change. Only updated the site thinking I would at least see a landing page.

**Comment by UbuntuEvangelist** [comment]
404 page not found though i have update /etc/hosts  (set: 0.0.0.0 www.app.local)

**Comment by Galaxy-Traveler** [comment]
> 404 page not found though i have update /etc/hosts (set: 0.0.0.0 [www.app.local](http://www.app.local))

update /etc/hosts   0.0.0.0 www.ardax.com.ar

**Comment by UbuntuEvangelist** [comment]
> 0.0.0.0 [www.ardax.com.ar](http://www.ardax.com.ar)

![Screenshot from 2020-06-05 15-05-20](https://user-images.githubusercontent.com/1058663/83858238-fd231580-a73d-11ea-90e8-5aae607af616.png)
yes i did it but now its only shows a blank page

**Comment by Galaxy-Traveler** [comment]
git clone https://github.com/openware/baseapp.git
cd baseapp
nano config-overrides.js
delete lines 31-33
docker build -t frontend/baseapp:2.4.0 .
cd opendax
nano config/app.yml
frontend: quay.io/openware/baseapp:latest
to
frontend: frontend/baseapp:2.4.0
rake service:all

**Comment by Galaxy-Traveler** [comment]
> I have the same blank page issue on the site. The browser console states it is missing data so must be something missing in the app.yml I didn't change. Only updated the site thinking I would at least see a landing page.
git clone https://github.com/openware/baseapp.git
cd baseapp
nano config-overrides.js
delete lines 31-33
docker build -t frontend/baseapp:2.4.0 .
cd opendax
nano config/app.yml
frontend: quay.io/openware/baseapp:latest
to
frontend: frontend/baseapp:2.4.0
rake service:all

**Comment by lackorol** [comment]
> > I have the same blank page issue on the site. The browser console states it is missing data so must be something missing in the app.yml I didn't change. Only updated the site thinking I would at least see a landing page.
> > git clone https://github.com/openware/baseapp.git
> > cd baseapp
> > nano config-overrides.js
> > delete lines 31-33
> > docker build -t frontend/baseapp:2.4.0 .
> > cd opendax
> > nano config/app.yml
> > frontend: quay.io/openware/baseapp:latest
> > to
> > frontend: frontend/baseapp:2.4.0
> > rake service:all

How to build from git baseapp.git?
You are making change in config-overrdes.js but
then pulling image from docker CN.

**Comment by UbuntuEvangelist** [comment]
> git clone https://github.com/openware/baseapp.git
> cd baseapp
> nano config-overrides.js
> delete lines 31-33
> docker build -t frontend/baseapp:2.4.0 .
> cd opendax
> nano config/app.yml
> frontend: quay.io/openware/baseapp:latest
> to
> frontend: frontend/baseapp:2.4.0
> rake service:all

Its not works

  peatio: quay.io/openware/peatio:2.4.7
  barong: quay.io/openware/barong:2.4.1
  frontend: frontend/baseapp:2.3.0 
  tower: quay.io/openware/tower:2.4.1

baseapp:2.3.0 works for me into Ubuntu 18.04 LTS 64 bit Linux

**Comment by lackorol** [comment]
Did somebody solved issue? Removing lines in config-overrides doesn't work.

**Comment by UbuntuEvangelist** [comment]
@lackorol yes i have solve this issue. use this

peatio: quay.io/openware/peatio:2.4.7
barong: quay.io/openware/barong:2.4.1
frontend: frontend/baseapp:2.3.0
tower: quay.io/openware/tower:2.4.1

**Comment by dpatsora** [comment]
Hi!

We are closing this issue due to it's been resolved

Sincerely yours,
OW team

**Comment by bytelong** [comment]
> Hi!
> 
> We are closing this issue due to it's been resolved
> 
> Sincerely yours, OW team

No, it is still doesn't work , till now. please fix it!
