### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by fullmad** [openware/opendax#155]
404 Error. 
http://173.249.50.73/
SSH username: app
SSH password: 123456

Tried whole day, but couldn't find how to solve.

`docker-compose up -d peatio barong gateway
Recreating opendax_barong_1  ... done
Recreating opendax_gateway_1 ... done
Recreating opendax_peatio_1  ... done
----- Starting the frontend -----
docker-compose up -d frontend
Recreating opendax_frontend_1 ... done
----- Starting the tower -----
docker-compose up -d tower
Recreating opendax_tower_1 ... done
----- Starting utils -----
docker-compose up -d mailer
Recreating opendax_mailer_1 ... done
----- Starting peatio daemons -----
docker-compose up -d ranger withdraw_audit blockchain cron_job upstream deposit_collection deposit_collection_fees deposit_coin_address withdraw_coin influx_writer matching order_processor trade_executor
Recreating opendax_deposit_coin_address_1 ... 
Recreating opendax_deposit_coin_address_1    ... done
Recreating opendax_matching_1                ... done
Recreating opendax_withdraw_audit_1          ... done
Recreating opendax_cron_job_1                ... done
Recreating opendax_deposit_collection_fees_1 ... done
Recreating opendax_order_processor_1         ... done
Recreating opendax_withdraw_coin_1           ... done
Recreating opendax_influx_writer_1           ... done
Recreating opendax_deposit_collection_1      ... done
Recreating opendax_blockchain_1              ... done
Recreating opendax_upstream_1                ... done
Recreating opendax_trade_executor_1          ... done`

**Comment by dpatsora** [comment]
Hello!
To access the platform you should use URL instead of trying to access via IP address.
Here you can read how reverse proxies work http://nginx.org/en/docs/http/request_processing.html

Sincerely yours,
Openware Team

**Comment by dpatsora** [comment]
Hi!

We are closing this issue due to it's been resolved

Sincerely yours, 
OW team
