### ISSUE TITLE
Frontend not showing up

### ISSUE THREAD

**Issue by behnammby** [openware/opendax#157]
Installing a fresh new opendax on Debian 10, ruby 2.6.5.

installing docker and docker-compose
installing ruby rvm
git clone opendax
install bundler
bundle install
creating vault
rake service:all[start]

and all services are up, no error

but when opening frontend in browser by typing the domain configured in config/app.yaml, I see the following error in the console and nothing is displayed but a blank page with gray background.

main.d2e6ef35.js:1 Uncaught ReferenceError: data is not defined
at main.d2e6ef35.js:1
at _0x50e05e (main.d2e6ef35.js:1)
at _0x474aea (main.d2e6ef35.js:1)
at main.d2e6ef35.js:1
at main.d2e6ef35.js:1

**Comment by Galaxy-Traveler** [comment]
https://medium.com/openware/deploy-your-own-crypto-trading-platform-opendax-on-digital-ocean-in-15-minutes-24ca0308fbb3
====================
Prior to this tutorial I’ve prepared a script that will set up a docker-compose and ruby environment so that we can start immediately. So run the following command in your VM’s terminal
curl https://gist.githubusercontent.com/alinetskyi/cfc95dbce01d9452d93726e9157e89a1/raw/6c2a60e683e57a07b0b549ad1838d11bb4805c01/setup.sh | bash
Now our VM is ready and we can clone OpenDAX:
git clone https://github.com/openware/opendax.git
cd opendax
bundle install

**Comment by behnammby** [comment]
I do appreciate for your reply. I followed the instruction. The error still appears and nothing is shown. I think there is something wrong with my config/app.yaml. 
I've  only configured domain and vault. Is there anything else that I need to configure to see frontend with no errors?
I know that I need to configure thnigs later, but at this step I want to see empty frontend first and develop later. 

Regards

**Comment by sergzuko** [comment]
Its working anly  with www.app.local domain in app.yml config. If you change it on any - its not working.

Investigating

**Comment by sergzuko** [comment]
Do idea. opendax work only with www.app.local domain

Uncaught ReferenceError: data is not defined
    at main.954b73f0.js:1
    at _0x3fc6e7 (main.954b73f0.js:1)
    at _0x312705 (main.954b73f0.js:1)
    at main.954b73f0.js:1
    at main.954b73f0.js:1

**Comment by sergzuko** [comment]
in same time my old installation work with custom domain

**Comment by sergzuko** [comment]
its working with quay.io/openware/baseapp:2.3.26
not with latest

**Comment by sergzuko** [comment]
same issue but closed
https://github.com/openware/baseapp/issues/178

**Comment by freakcoderz** [comment]
The installer gives me errors and doesn't even finish using Ubuntu 16. Doing it manually and using an older base/peatio/ect works for me.

**Comment by behnammby** [comment]
Thank you for your answers. 

> its working with quay.io/openware/baseapp:2.3.26
> not with latest

Wow! I do appreciate for your reply. I changed to quay.io/openware/baseapp:2.3.26 and now it's work like a charm! Thank you so much.

**Comment by behnammby** [comment]
> same issue but closed
> [openware/baseapp#178](https://github.com/openware/baseapp/issues/178)

Yeap! It's me. I'd raised the issue there before sending it here.

**Comment by behnammby** [comment]
> The installer gives me errors and doesn't even finish using Ubuntu 16. Doing it manually and using an older base/peatio/ect works for me.

Thank you for your reply. I do appreciate.

**Comment by sergzuko** [comment]
Linux Gun, [09.06.20 17:24]
[In reply to Sergei Dindikov]
git clone https://github.com/openware/baseapp.git
cd baseapp
nano config-overrides.js
delete lines 31-33
docker build -t frontend/baseapp:2.4.0 .
cd opendax
nano config/app.yml
frontend: quay.io/openware/baseapp:latest
to
frontend: frontend/baseapp:2.4.0
rake service:all

Linux Gun, [09.06.20 17:26]
[In reply to Sergei Dindikov]
use this peatio: quay.io/openware/peatio:2.4.7
barong: quay.io/openware/barong:2.4.1
frontend: frontend/baseapp:2.3.0
tower: quay.io/openware/tower:2.4.1

**Comment by behnammby** [comment]
> Linux Gun, [09.06.20 17:24]
> [In reply to Sergei Dindikov]
> git clone https://github.com/openware/baseapp.git
> cd baseapp
> nano config-overrides.js
> delete lines 31-33
> docker build -t frontend/baseapp:2.4.0 .
> cd opendax
> nano config/app.yml
> frontend: quay.io/openware/baseapp:latest
> to
> frontend: frontend/baseapp:2.4.0
> rake service:all
> 
> Linux Gun, [09.06.20 17:26]
> [In reply to Sergei Dindikov]
> use this peatio: quay.io/openware/peatio:2.4.7
> barong: quay.io/openware/barong:2.4.1
> frontend: frontend/baseapp:2.3.0
> tower: quay.io/openware/tower:2.4.1

Thank you very much. I appreciate.

**Comment by behnammby** [comment]
> Linux Gun, [09.06.20 17:24]
> [In reply to Sergei Dindikov]
> git clone https://github.com/openware/baseapp.git
> cd baseapp
> nano config-overrides.js
> delete lines 31-33
> docker build -t frontend/baseapp:2.4.0 .
> cd opendax
> nano config/app.yml
> frontend: quay.io/openware/baseapp:latest
> to
> frontend: frontend/baseapp:2.4.0
> rake service:all
> 
> Linux Gun, [09.06.20 17:26]
> [In reply to Sergei Dindikov]
> use this peatio: quay.io/openware/peatio:2.4.7
> barong: quay.io/openware/barong:2.4.1
> frontend: frontend/baseapp:2.3.0
> tower: quay.io/openware/tower:2.4.1

**Comment by chebyte** [comment]
I just try with the last realease with a custom domain and I have the same problem, the same empty gray page

any updates? why is closed?

**Comment by chebyte** [comment]
about fixeds related here:

> quay.io/openware/baseapp:2.3.26
  I think that it is a very old version, the last one is 2.5.x

> Linux Gun, [09.06.20 17:24]
> [In reply to Sergei Dindikov]
> git clone https://github.com/openware/baseapp.git
> cd baseapp
> nano config-overrides.js
> delete lines 31-33
> docker build -t frontend/baseapp:2.4.0 .
> cd opendax
> nano config/app.yml
> frontend: quay.io/openware/baseapp:latest
> to
> frontend: frontend/baseapp:2.4.0
> rake service:all
> 
 I think that is not a valid solution, but btw is old version and is not working too
