### ISSUE TITLE
rake service:all  rake aborted

### ISSUE THREAD

**Issue by ziadzoalnoon** [openware/opendax#16]
docker-compose up -d proxy
rake aborted!
Command failed with status (127): [docker-compose up -d proxy...]
lib/tasks/service.rake:25:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:33:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:230:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:253:in `block (2 levels) in <top (required)>'
/home/zezo3/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/zezo3/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/home/zezo3/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => service:proxy

**Comment by gelinger777** [comment]
@ziadzoalnoon  install docker compose.

**Comment by Along-WG** [comment]
`rake service:all`    Have the same mistake
`sudo docker-compose up`  It's bootable

How do you get started properly with the `rake service:all`  command?

**Comment by Shreybhardwaj97** [comment]
@ziadzoalnoon HI you can resolve the issue by installing the docker compose

sudo apt-get update
sudo apt-get upgrade
Check the curl command by entering:
curl

To install curl, enter the following:
sudo apt install curl
Download the Latest Docker Compose Version
1. To download the latest version of Docker Compose, use the command:
sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose


sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version

**Comment by dpatsora** [comment]
Hi!

We are closing this issue due to it's been resolved.

Sincerely yours,
OW team
