### ISSUE TITLE
How to make trading running for ETH/USD

### ISSUE THREAD

**Issue by venkateshsys** [openware/opendax#165]
I have started the baseapp with all services running. But from the logs of the blockchain container, it gives this error.
```
{"level":"ERROR","time":"2020-06-20 06:10:55","message":"/home/app/lib/peatio/ethereum/blockchain.rb:60:in `rescue in latest_block_number'\n/home/app/lib/peatio/ethereum/blockchain.rb:57:in `latest_block_number'\n/home/app/app/services/blockchain_service.rb:16:in `latest_block_number'\n/home/app/app/workers/daemons/blockchain.rb:22:in `process'\n/home/app/app/workers/daemons/blockchain.rb:9:in `block (3 levels) in run'"}
{"level":"WARN","time":"2020-06-20 06:10:55","message":"Error: Failed to open TCP connection to parity:8545 (getaddrinfo: Name or service not known). Sleeping for 10 seconds"}
```

![image](https://user-images.githubusercontent.com/48546261/85194229-a21b2200-b2ea-11ea-9790-f7e850fdc0a2.png)

Is graph depends on that docker error? So how to achieve graph runs properly

**Comment by freakcoderz** [comment]
Have you made any trades for the graph to show something? Is your ETH node set up and linked?

**Comment by venkateshsys** [comment]
No! I didn't do any trading yet.
Parity node is always restarting. It shows these logs 
```
Option '--warp' does nothing. It's on by default.
Error upgrading parity data: CannotCreateConfigPath(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
```
whereas in my blockchain container, it has Error: Failed to open TCP connection to parity:8545.
Clarify this for the initial graph to show up it is needed to do any trading? @freakcoderz

**Comment by freakcoderz** [comment]
Yes, the graph is to show the change in prices as trades are done. No trades, no graph. The parity node you are trying to connect to needs to be set up by you. I haven't successfully added any coins yet, so no help from me there.

**Comment by thatshailesh** [comment]
@venkateshsys  hello, were u able to fix this issue of parity node?
