### ISSUE TITLE
Error: Failed to open TCP connection to parity:8545

### ISSUE THREAD

**Issue by venkateshsys** [openware/opendax#188]
Frontend is loading perfectly but my backend parity container fails.
Configuration file for the parity in cryptonodes.yaml file:

![image](https://user-images.githubusercontent.com/48546261/87226187-c7fa8a80-c3af-11ea-9a05-bc55431c8c5c.png)

When I run the logs for
1. blockchain container, it gives this error.
```
{"level":"ERROR","time":"2020-06-20 06:10:55","message":"/home/app/lib/peatio/ethereum/blockchain.rb:60:in `rescue in latest_block_number'\n/home/app/lib/peatio/ethereum/blockchain.rb:57:in `latest_block_number'\n/home/app/app/services/blockchain_service.rb:16:in `latest_block_number'\n/home/app/app/workers/daemons/blockchain.rb:22:in `process'\n/home/app/app/workers/daemons/blockchain.rb:9:in `block (3 levels) in run'"}
{"level":"WARN","time":"2020-06-20 06:10:55","message":"Error: Failed to open TCP connection to parity:8545 (getaddrinfo: Name or service not known). Sleeping for 10 seconds"}
```
2. parity container, it gives this
```
Option '--warp' does nothing. It's on by default.
Error upgrading parity data: CannotCreateConfigPath(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
```
How to resolve this error to make parity running?

Thanks in advance

**Comment by Galaxy-Traveler** [comment]
Parity must be installed
sudo snap install parity
sudo snap install parity-ui
cryptonodes.yaml
volumes:
      - ../data/parity:/home/parity/.local/share/io.parity.ethereum
to
../data/parity:/home/app/snap/parity/16707/.local/share/io.parity.ethereum

**Comment by venkateshsys** [comment]
Thanks @Galaxy-Traveler :) 

Now I am able to connect with parity and also bitcoind, here the problem I am facing is that my wallet balance not showing in Frontend. I have transferred **kovan ETH** to the generated address **0xa8f4f82fadc6757e8d7adeacbb798c5a6e8d8ef8**
For ref here is the link for tx: [LINK]
(https://kovan.etherscan.io/tx/0xc7c0051e0f5acaceeea7ecea2065f1ae8e74b04f9163da353102f27fa7dbb38e)

![image](https://user-images.githubusercontent.com/48546261/87686845-a24ff580-c7a2-11ea-91ea-9088d7ba1266.png)
These are the parity logs, syncing process works well, all the **kovan** transaction blocks are imported fine. (Same as for bitcoind, all the blocks are syncing fine)

![image](https://user-images.githubusercontent.com/48546261/87687403-4f2a7280-c7a3-11ea-87cf-6e46bb371aab.png)


How will the **kovan ETH / Testnet BTC** reflects in the Frontend?

Thanks in advance

**Comment by Galaxy-Traveler** [comment]
Did you put the deposit address in your wallet?

**Comment by venkateshsys** [comment]
Wallet means?? In Database? @Galaxy-Traveler

**Comment by Galaxy-Traveler** [comment]
deposit wallet address
=======
deposit
hot
warm

**Comment by venkateshsys** [comment]
Yeah! I have added wallet addresses in all three wallet types @Galaxy-Traveler

**Comment by venkateshsys** [comment]
It depends upon the blockchain height i.e., ETH and BTC blockchain. In the tower the height will be updated slowly, whenever the height meets with your transaction block, it will be updated. So that the wallet balance will show in UI and in deposit history as well. 
Another easy solution, change the height for both blockchains to the current height of the blockchain (because your transactions will be stored after this block Id, no transaction of yours will be there below the current block) while setup the exchange platform.

**Comment by mahalamobile** [comment]
have the same issue, i have setup docker container for bitcoind, have all rpc username and password, i get when looking to retrieve deposit address either ""Failed to decode cookies"" or JWT error, and in bitcoin logs giving TCP errors saying cant connect

what am i missing here? i have hot, cold and warm wallets and also added newaddresses via the admin portal

please help, just want to setup a basic btc exchange ;)

![image](https://user-images.githubusercontent.com/7688360/94273645-f581b980-ff44-11ea-89f0-5ab5f7fb3815.png)

also how do i get rid of the ETH at the top, this a frontend issue as ive removed all reference to ETH in config files and also parity deamon

thanks
