### ISSUE TITLE
After installed all on Ubuntu 18.04 Blank Dark Blue Page

### ISSUE THREAD

**Issue by alcoxbiz** [openware/opendax#204]
Hello !
 After installed opendax on fresh ubuntu 18.04 VPS i get only a blue main page.
I have done this 

    Take clear Ubuntu 18.04
    clone Opendax
    chmod +x bin/install.sh
    bin/install.sh
    Install RVM
    Restart the machine to apply docker configurations
    bundle install
    rake service:all

All dockers up without error result https://exchange.alcox.biz 

Any hint whats wrong ?

Regards

**Comment by venkateshsys** [comment]
It seems that you have not added your domain in _.domains_ file of your baseapp. Make sure that add your domain **.alcox.biz** to _.domains_ file to the list already present. 
**Example:** localhost,.app.local,.openware.com,......,**.alcox.biz** [Observer here add along with dot]
Rebuild the image again, redeploy and hit your URL

Thanks

**Comment by alcoxbiz** [comment]
Al done, it was in baseapp problem.

**Comment by alcoxbiz** [comment]
You have to delte some rows and adjust.

**Comment by cryptoruby** [comment]
@alcoxbiz how did you fix it. I want to run it without installing opendax

I have files at 

`docker exec -it exchange_frontend_1 sh
`
but blue blank page still comes.

**Comment by BTCDIRECT** [comment]
anyone know how to fix blue screen yet

**Comment by crackfoo** [comment]
Where is the .domains file?
