### ISSUE TITLE
Error: Version in "./compose/app.yaml" is unsupported.

### ISSUE THREAD

**Issue by ictinc** [openware/opendax#205]
Running Ubuntu 16.04 on GCP.
Docker version 19.03.12, build 48a66213fe
docker-compose version 1.8.0, build unknown

After running:
`rake service:all`

I get the following:
`----- Starting the proxy -----
docker-compose up -d proxy
ERROR: Version in "./compose/app.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
rake aborted!
Command failed with status (1): [docker-compose up -d proxy...]
lib/tasks/service.rake:25:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:33:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:277:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:302:in `block (2 levels) in <top (required)>'
/home/app/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/app/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/home/app/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => service:proxy
(See full trace by running task with --trace)
`

**Comment by alcoxbiz** [comment]
use docker compose 1.23.1

**Comment by ictinc** [comment]
Thanks, that worked.
I'm now however facing the same issue as in [https://github.com/openware/opendax/issues/204](url).
What do you mean by _.domains_ file? Before issuing `rake service:all` I've added my domain to config/app.yml/, to which other file should I add my domain?

**Comment by alcoxbiz** [comment]
sorry under your link is nothing.
Which problem you have

**Comment by ictinc** [comment]
The problem of only a blue page showing

**Comment by alcoxbiz** [comment]
aah ok just follow this small guide

git clone https://github.com/openware/baseapp.git
cd baseapp
nano config-overrides.js
delete lines 31-33
docker build -t frontend/baseapp:2.4.0 .
cd
cd opendax
nano config/app.yml
change:
frontend: quay.io/openware/baseapp:2.4.1 # Check on quay.io/openware/baseapp for latest tags
to
frontend: frontend/baseapp:2.4.0
rake service:all

**Comment by ictinc** [comment]
Thanks, I'm gonna give that a go..:)

**Comment by alcoxbiz** [comment]
if you want get the landing page viewed then change also
nano /baseapp/src/routes/Layout/index.tsx
Line 8 to:
import { minutesUntilAutoLogout, sessionCheckInterval } from '../../api';
Line 257 to:
<Route exact={true} path="/" component={LandingScreen} />

**Comment by alcoxbiz** [comment]
hmm dont show code fro line 257
line 257 must be "<Route exact={true} path="/" component={LandingScreen} />"

**Comment by alcoxbiz** [comment]
`<Route exact={true} path="/" component={LandingScreen} />`

**Comment by ictinc** [comment]
Thank you so much for you help. Everything's working now.
