### ISSUE TITLE
Ropsten Testnet ETH testing withdrawals of funds not working

### ISSUE THREAD

**Issue by mehmet-biter** [openware/opendax#233]
Ropsten Testnet ETH testing withdrawals of funds not working
erc20 does not work

I need help with this

![IMG_20201024_150948_753](https://user-images.githubusercontent.com/14812826/97081412-03416200-160b-11eb-93be-df94699091b2.jpg)
![IMG_20201024_150945_843](https://user-images.githubusercontent.com/14812826/97081420-0d636080-160b-11eb-80fd-f29b67fe2290.jpg)
![IMG_20201024_150942_442](https://user-images.githubusercontent.com/14812826/97081424-13594180-160b-11eb-810b-4c036d4ba5a2.jpg)
![IMG_20201024_150937_716](https://user-images.githubusercontent.com/14812826/97081431-19e7b900-160b-11eb-868a-b93929d5edea.jpg)

**Comment by alinetskyi** [comment]
Hi, can you provide some screenshots of logs please ?
You should checkout the logs of withdraw daemon
