### ISSUE TITLE
Bitcoin Create a new account

### ISSUE THREAD

**Issue by Galaxy-Traveler** [openware/opendax#240]
cd opendax
curl -H "Content-Type: application/json" --data '{"method": "getnewaddress"}' admin:changeme@bitcoind:8332
Answer
curl: (28) Failed to connect to bitcoind port 8332: Connection timed out

**Comment by Galaxy-Traveler** [comment]
Same answer to Litecoin

**Comment by NCEX** [comment]
add to cryptonodes.yaml.erb to bitcoind 
    ports:
      - "127.0.0.1:8332:8332"

**Comment by Galaxy-Traveler** [comment]
cd opendax/templates/compose
nano cryptonodes.yaml.erb
  bitcoind:
    image: quay.io/openware/bitcoind:0.17.1
    restart: always
    volumes:
      - ../data/bitcoin:/bitcoin
      - ../config/bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf

  litecoind:
    image: quay.io/openware/litecoind:0.16.3
    restart: always
    volumes:
      - ../data/litecoin:/litecoin
      - ../config/litecoin.conf:/litecoin/litecoin.conf
TO
  bitcoind:
    image: quay.io/openware/bitcoind:0.17.1
    restart: always
    volumes:
      - ../data/bitcoin:/bitcoin
      - ../config/bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
    ports:
      - "127.0.0.1:8332:8332"

  litecoind:
    image: quay.io/openware/litecoind:0.16.3
    restart: always
    volumes:
      - ../data/litecoin:/litecoin
      - ../config/litecoin.conf:/litecoin/litecoin.conf
    ports:
      - "127.0.0.1:9332:9332"
============
cd ../..

curl --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"getblockchaininfo","params":[]}' -H 'content-type:text/plain;' http://admin:changeme@127.0.0.1:8332/

Answer
OK

**Comment by Galaxy-Traveler** [comment]
> add to cryptonodes.yaml.erb to bitcoind
> ports:
> - "127.0.0.1:8332:8332"

Thanks for your help
