### ISSUE TITLE
Vault::HTTPConnectionError:

### ISSUE THREAD

**Issue by Galaxy-Traveler** [openware/opendax#246]
Vault::HTTPConnectionError: The Vault server at `http://127.0.0.1:8200' is not currently
accepting connections. Please ensure that the server is running and that your
authentication information is correct.

The original error was `Vault::PersistentHTTP::Error'. Additional information (if any) is
shown below:

    connection refused: 127.0.0.1:8200

**Comment by Galaxy-Traveler** [comment]
docker-compose logs -f vault
================
app@mkwayexchange:~/opendax$ docker-compose logs -f vault
Attaching to mkwayexchange_vault_1
vault_1                 | ==> Vault server configuration:
vault_1                 |
vault_1                 |                      Cgo: disabled
vault_1                 |               Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
vault_1                 |                Log Level: info
vault_1                 |                    Mlock: supported: true, enabled: true
vault_1                 |            Recovery Mode: false
vault_1                 |                  Storage: file
vault_1                 |                  Version: Vault v1.3.0
vault_1                 |
vault_1                 | ==> Vault server started! Log data will stream in below:
vault_1                 |
vault_1                 | 2020-12-06T09:45:40.427Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
vault_1                 | 2020-12-06T09:45:40.427Z [WARN]  no `api_addr` value specified in config or in VAULT_API_ADDR; falling back to detection if possible, but this value should be manually set
vault_1                 | 2020-12-06T09:46:14.056Z [INFO]  core: seal configuration missing, not initialized
vault_1                 | 2020-12-06T09:46:15.079Z [ERROR] core: no seal config found, can't determine if legacy or new-style shamir
vault_1                 | 2020-12-06T09:46:15.079Z [INFO]  core: security barrier not initialized
vault_1                 | 2020-12-06T09:46:15.080Z [INFO]  core: security barrier initialized: stored=1 shares=5 threshold=3
vault_1                 | 2020-12-06T09:46:15.080Z [INFO]  core: post-unseal setup starting
vault_1                 | 2020-12-06T09:46:15.091Z [INFO]  core: loaded wrapping token key
vault_1                 | 2020-12-06T09:46:15.091Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
vault_1                 | 2020-12-06T09:46:15.092Z [INFO]  core: no mounts; adding default mount table
vault_1                 | 2020-12-06T09:46:15.092Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
vault_1                 | 2020-12-06T09:46:15.093Z [INFO]  core: successfully mounted backend: type=system path=sys/
vault_1                 | 2020-12-06T09:46:15.093Z [INFO]  core: successfully mounted backend: type=identity path=identity/
vault_1                 | 2020-12-06T09:46:15.096Z [INFO]  core: successfully enabled credential backend: type=token path=token/
vault_1                 | 2020-12-06T09:46:15.096Z [INFO]  core: restoring leases
vault_1                 | 2020-12-06T09:46:15.097Z [INFO]  rollback: starting rollback manager
vault_1                 | 2020-12-06T09:46:15.097Z [INFO]  expiration: lease restore complete
vault_1                 | 2020-12-06T09:46:15.097Z [INFO]  identity: entities restored
vault_1                 | 2020-12-06T09:46:15.097Z [INFO]  identity: groups restored
vault_1                 | 2020-12-06T09:46:15.097Z [INFO]  core: post-unseal setup complete
vault_1                 | 2020-12-06T09:46:15.099Z [INFO]  core: root token generated
vault_1                 | 2020-12-06T09:46:15.099Z [INFO]  core: pre-seal teardown starting
vault_1                 | 2020-12-06T09:46:15.099Z [INFO]  rollback: stopping rollback manager
vault_1                 | 2020-12-06T09:46:15.099Z [INFO]  core: pre-seal teardown complete
vault_1                 | 2020-12-06T09:46:18.191Z [INFO]  core.cluster-listener: starting listener: listener_address=0.0.0.0:8201
vault_1                 | 2020-12-06T09:46:18.192Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=[::]:8201
vault_1                 | 2020-12-06T09:46:18.192Z [INFO]  core: post-unseal setup starting
vault_1                 | 2020-12-06T09:46:18.192Z [INFO]  core: loaded wrapping token key
vault_1                 | 2020-12-06T09:46:18.192Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
vault_1                 | 2020-12-06T09:46:18.192Z [INFO]  core: successfully mounted backend: type=system path=sys/
vault_1                 | 2020-12-06T09:46:18.193Z [INFO]  core: successfully mounted backend: type=identity path=identity/
vault_1                 | 2020-12-06T09:46:18.193Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
vault_1                 | 2020-12-06T09:46:18.194Z [INFO]  core: successfully enabled credential backend: type=token path=token/
vault_1                 | 2020-12-06T09:46:18.194Z [INFO]  core: restoring leases
vault_1                 | 2020-12-06T09:46:18.197Z [INFO]  rollback: starting rollback manager
vault_1                 | 2020-12-06T09:46:18.198Z [INFO]  identity: entities restored
vault_1                 | 2020-12-06T09:46:18.198Z [INFO]  expiration: lease restore complete
vault_1                 | 2020-12-06T09:46:18.198Z [INFO]  identity: groups restored
vault_1                 | 2020-12-06T09:46:18.198Z [INFO]  core: post-unseal setup complete
vault_1                 | 2020-12-06T09:46:18.198Z [INFO]  core: vault is unsealed
vault_1                 | 2020-12-06T09:46:20.272Z [INFO]  core: successful mount: namespace= path=totp/ type=totp
vault_1                 | 2020-12-06T09:46:21.296Z [INFO]  core: successful mount: namespace= path=transit/ type=transit
vault_1                 | 2020-12-06T09:46:23.373Z [INFO]  core: successful mount: namespace= path=secret/ type=kv

**Comment by lucagrossi** [comment]
Hi Galaxy-Traveler: How did you solve this? Did this also happen when you changed Peatio version?
