### ISSUE TITLE
Bitcoin/Litecoin encrypted wallet

### ISSUE THREAD

**Issue by Galaxy-Traveler** [openware/opendax#249]
What is the command to encrypt the wallets.
------------
Create a new account
-------
curl -H "Content-Type: application/json" --data '{"method": "getnewaddress"}' rpcuser:rpcpassword@ip:port
--------
Account info
----------
curl -H "Content-Type: application/json" --data '{"method": "getaccount", "params": ["bchtest:qpkgrpazps220qtnzvlvlcm62urtnq0edv7ufjr95n"]}' rpcuser:rpcpassword@ip:port
-----------
Wallet encryption is not specified.
https://github.com/openware/images/tree/master/bitcoind

**Comment by Kohelbekker** [comment]
There is link to Bitcoin RPC API at the bottom of https://github.com/openware/images/tree/master/bitcoind. 

There you can find the `encryptwallet` method, so JSON-RPC call should look like that:
`curl -H "Content-Type: application/json" --data '{"method": "encryptwallet", "params": ["my pass phrase"]}' rpcuser:rpcpassword@ip:port`
