### ISSUE TITLE
the balance does not appear in my wallet after sending ether

### ISSUE THREAD

**Issue by jordanlanch** [openware/opendax#253]
I made the configuration of the wallets

![image](https://user-images.githubusercontent.com/24902096/102693768-f5632400-41ea-11eb-923a-9b72af502162.png)

send ehter to this wallet
![image](https://user-images.githubusercontent.com/24902096/102693784-0e6bd500-41eb-11eb-92dc-55198cff2ff5.png)

send ehter to this wallet, but it is not reflected in the balance
https://ropsten.etherscan.io/address/0x802ebfcd9e83e0d60cb88d250f52f2e8d11da365

**Comment by Ali-Shaikh** [comment]
Did you find a solution for this? I am using Ropsten also but not getting the balance shown in wallet
