### ISSUE TITLE
cryptonodes.yaml for Ripple

### ISSUE THREAD

**Issue by Galaxy-Traveler** [openware/opendax#255]
Who knows how to add rippled in cryptonodes.yaml?

**Comment by realsofttechiz** [comment]
i know about this

**Comment by MkwayCoin** [comment]
rippled:
    image: ripple/rippled:latest
    restart: always
    command: rippled
    volumes:
      - ../data/ripple:/home/app/opendax/data/ripple
    ports:
      - "51235:51235"
      - "51234:51234"
    expose:
      - "51235"
      - "51234"
    ports:
      - "127.0.0.1:51234:51234"

What if I'm not mistaken?
