### ISSUE TITLE
This feature is unavailable 

### ISSUE THREAD

**Issue by ProfProfcompile** [openware/opendax#26]
Hi 

Why does the platform state " this feature is unavailable - For unlocking please visit openware.com"

This is for 2fa , theme and phone verification . 

- The only option available on openware is opendaxlite . If i do phone verification this gives a popup some went wrong . 

Please advise

**Comment by dpatsora** [comment]
Hi @ProfProfcompile! 
Thanks for reaching out.

OpenDAX used to contain demo functionality of OW stack. So advanced features like phone verification was blocked. But now, OpenDAX contains whole functionality. 

Recently we released 2-5-stable. Looking forward to your feedback)

Sincerely yours, 
OW team
