### ISSUE TITLE
Hello, I want to add new links to the site

### ISSUE THREAD

**Issue by mehmet-biter** [openware/opendax#261]
Hello, I want to add new links to the site. Can you help me with this?
![fff](https://user-images.githubusercontent.com/14812826/104138677-bcb40600-53b6-11eb-848c-304312929c45.PNG)

**Comment by mehmet-biter** [comment]
no one to help me

**Comment by dpatsora** [comment]
Hi @mehmet-biter!

Sorry for the late response.
Please, check the following code https://github.com/openware/baseapp/blob/7fd98c34475bd277c8a67338ef4215c190a63f30/src/screens/LandingScreen/index.tsx#L213-L249

To add new column:
```
<div className="pg-landing-screen__footer__wrap__navigation__col"></div>
```

To add new link:
```
<Link to="https://github.com">TITLE</Link>
```

Sincerely yours,
Openware team

**Comment by dpatsora** [comment]
Feel free to reopen this issue if you have any questions.

Sincerely yours, 
Openware team
