### ISSUE TITLE
BUG (Tower): Blockchain settings - server field doesn't display current server 

### ISSUE THREAD

**Issue by crackfoo** [openware/opendax#300]
Hi, 

I'm not sure if this was/is intentional but the text box for the blockchain server doesn't display the currently set server. It simply displays the default suggestion http://geth:8545

Thanks

**Comment by crackfoo** [comment]
It's also the same issue on the wallet settings page. The URI which is set, is not displayed.

**Comment by talhadar90** [comment]
any fixes to this?

**Comment by ultra-pool** [comment]
Its still doing this.

**Comment by crackfoo** [comment]
> any fixes to this?

Not that I'm aware of.
