### ISSUE TITLE
Can i change docker image ?

### ISSUE THREAD

**Issue by Scarletlen** [openware/opendax#358]
I clone barong repo and buid docker image . i change the opendax docker image but i can't start service.
![image](https://user-images.githubusercontent.com/62289804/133545847-b4efbb92-57cd-4144-9096-b6e9ace3cb1c.png)

**Comment by kanakan34** [comment]
> I clone barong repo and buid docker image . i change the opendax docker image but i can't start service. ![image](https://user-images.githubusercontent.com/62289804/133545847-b4efbb92-57cd-4144-9096-b6e9ace3cb1c.png)

opendax default version 2.6 and you can not use barong/master docker image. you need use barong 2-6-stable
