### ISSUE TITLE
HI guys...I got this error..Rake aborted!!!

### ISSUE THREAD

**Issue by violetdroidxz** [openware/opendax#382]
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [docker-compose run --rm peatio bash -c "./...]
lib/tasks/service.rake:119:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:126:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:206:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:223:in `block (2 levels) in <top (required)>'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/app/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/home/app/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => service:setup
(See full trace by running task with --trace)

**Comment by MonkeyD-Core** [comment]
give me full logs

**Comment by cryptonana** [comment]
> (See full trace by running task with --trace) rake aborted! Command failed with status (1): [docker-compose run --rm peatio bash -c "./...] lib/tasks/service.rake:119:in `start' lib/tasks/service.rake:7:in `call' lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>' lib/tasks/service.rake:126:in `block (2 levels) in <top (required)>' lib/tasks/service.rake:206:in `start' lib/tasks/service.rake:7:in `call' lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>' lib/tasks/service.rake:223:in `block (2 levels) in <top (required)>' /home/app/.rvm/gems/ruby-2.6.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>' /home/app/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval' /home/app/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `
> '
> Tasks: TOP => service:setup
> (See full trace by running task with --trace)

share full log

**Comment by MonkeyD-Core** [comment]
more debug log please

**Comment by mikechambers84** [comment]
Has this ever been solved? I have a similar issue but with the proxy component.
