### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by BTCDIRECT** [openware/opendax#45]
404 page not found

**Comment by UbuntuEvangelist** [comment]
same here, I am using Ubuntu 18.04 getting 404 page not found

**Comment by M-Adeel-Danish** [comment]
Did you guys found the solution? I am facing same problem.

**Comment by cleardex** [comment]
I managed the installation perfectly and to fix the hosts file correctly. However, any requests result in this error as well.
e.g. domain.com, domain.com/admin, tower.domain.com, monitor.domain.com
Has anyone managed to resolve these issues?

**Comment by shigristudy** [comment]
Facing same problem. Anyone who solve this issue

**Comment by shikhardb** [comment]
I am facing the same problem. Anything i open, goes to 404 not found.

**Comment by shigristudy** [comment]
Create subdomain and add in app.yml and use a droplet having 8gb ram minimum.

**Comment by shikhardb** [comment]
That works. Thanks. Also, I don't see the TradingView chart working. 
What may be the issues?

**Comment by luisemsuarez** [comment]
> Create subdomain and add in app.yml and use a droplet having 8gb ram minimum.

Hi.

Please can you explain this?

Thanks

**Comment by shigristudy** [comment]
> > Create subdomain and add in app.yml and use a droplet having 8gb ram minimum.
> 
> Hi.
> 
> Please can you explain this?
> 
> Thanks

Get a domain and create a subdomain as well and in app.yml file of project add subdomain in app.yml for viewing the result. 

Also the digital ocean droplet must have minimum 8 GB RAM otherwise will not work.

**Comment by luisemsuarez** [comment]
> > > Create subdomain and add in app.yml and use a droplet having 8gb ram minimum.
> > 
> > 
> > Hi.
> > Please can you explain this?
> > Thanks
> 
> Get a domain and create a subdomain as well and in app.yml file of project add subdomain in app.yml for viewing the result.
> 
> Also the digital ocean droplet must have minimum 8 GB RAM otherwise will not work.

Thanks for the fast response

does this mean it doesn't work on a pc to test locally?

**Comment by shigristudy** [comment]
I did not test on localhost. But It should work. Just need configuration.

**Comment by dpatsora** [comment]
Hi!


To test locally you need:
1. edit your `/etc/hosts` and add `0.0.0.0 www.app.local`
2. run `rake service:all`

Now your deployment is accessible on `www.app.local`

Don't hesitate to reopen the issue in case of any troubles.

Sincerely yours,
OW team

**Comment by sillydroid** [comment]
> Hi!
> 
> To test locally you need:
> 
> 1. edit your `/etc/hosts` and add `0.0.0.0 www.app.local`
> 2. run `rake service:all`
> 
> Now your deployment is accessible on `www.app.local`
> 
> Don't hesitate to reopen the issue in case of any troubles.
> 
> Sincerely yours,
> OW team

Hi dpatsora,

Can I ask please - for /etc/hosts you have written:

0.0.0.0 www.app.local

Should we replace this with:

[droplet IP address] www.[MYDOMAIN].com

Thank you!
