### ISSUE TITLE
rake vendor:clone

### ISSUE THREAD

**Issue by BTCDIRECT** [openware/opendax#46]
rake vendor:clone
----- Clone the frontend apps repos -----

git clone git@github.com:openware/baseapp.git vendor/frontend
Cloning into 'vendor/frontend'...
The authenticity of host 'github.com (140.82.118.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.118.4' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
rake aborted!
Command failed with status (128): [git clone git@github.com:openware/baseapp....]
lib/tasks/vendor.rake:7:in `block (3 levels) in <top (required)>'
lib/tasks/vendor.rake:6:in `each'
lib/tasks/vendor.rake:6:in `block (2 levels) in <top (required)>'
/home/deploy/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/home/deploy/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => vendor:clone
(See full trace by running task with --trace)

**Comment by dpatsora** [comment]
Hi!
Thanks for reaching out.

Now [Baseapp](https://github.com/openware/baseapp) is public repository.
Please, try again

Sincerely yours,
OW team
