### ISSUE TITLE
Bull

### ISSUE THREAD

**Issue by BTCDIRECT** [openware/opendax#47]
Oops!
It seems your license key is invalid

Visit Openware.com

Details
Id	765	   Domain assetdexx.com  Product	 OpenDAX Lite  Date of expiration	21 December 2019		         	      	
License Key IBIFS-VJFME-TPRVL-IMGX4-EVJPL .....??????????

**Comment by alxtrade** [comment]
Hi, I have the same problem, trying to research,

**Comment by dpatsora** [comment]
Hi!
Thanks for reaching out.

OpenDAX used to contain demo functionality of OW stack. So advanced features like phone verification was blocked. But now, OpenDAX contains whole functionality.

Recently we released 2-5-stable. Looking forward to your feedback)

Sincerely yours,
OW team
