### ISSUE TITLE
Add New currency?

### ISSUE THREAD

**Issue by rootserv** [openware/opendax#58]
How to add new currency in open dax i cannot find currency.yml to add rpc?

**Comment by alex1488x** [comment]
domain.xy/admin

**Comment by alex1488x** [comment]
url:http://user:pass@127.0.0.1
but only daemons with -cli works.

**Comment by ruby261** [comment]
@alex1488x for url port is required or not

**Comment by dpatsora** [comment]
Hi!
Thanks for reaching out.

Please check this [tutorial](https://medium.com/openware/how-to-configure-blockchain-node-in-the-tower-opendax-5e75e3264e18). Here we described full process of adding new blockchain, currency and wallets in OpenDAX

Sincerely yours, 
OW team
