### ISSUE TITLE
Deployment request - Margin for trading and cryptoactive futures

### ISSUE THREAD

**Issue by Guillerbr** [openware/opendax#63]
With the advancement of the currency futures market and the trader margin market, we can implement margin trading and futures system for the same, as the market has been adopting it.

**Comment by ruby261** [comment]
any plans to add this ?

**Comment by Guillerbr** [comment]
> algum plano para adicionar isso?

A leverage market and the option to operate in both buying and selling would be more appropriate. I still don't know exactly how it is done, but there are good cases of success in the margin / leverage market, such as: Binance, Bitmex, Okcoin and others that are bringing new products in this medium.

**Comment by danipolo** [comment]
+1

**Comment by ruby261** [comment]
+1

**Comment by Guillerbr** [comment]
+1

**Comment by dpatsora** [comment]
Hi!

This feature is in the backlog.
It probably will be added in the Finex.

Sincerely yours, 
OW team
