### ISSUE TITLE
Install failed to pull tower img

### ISSUE THREAD

**Issue by TTcoinDeveloper** [openware/opendax#7]
I tried to install but I got permission denied to pull tower error.
Is opendax open source?

**Comment by phuong17889** [comment]
same problem

**Comment by bzero** [comment]
you can clone it from github:

git clone https://github.com/rubykube/tower.git 

and build the docker image:

cd tower 
docker build -t tower .

then change config/app.yml inside opendax folder:
-  tower: quay.io/openware/tower:2.2.8
+  tower: tower:latest

**Comment by TTcoinDeveloper** [comment]
Which directory to clone tower?

**Comment by bzero** [comment]
I've cloned outside opendax directory, let us know if it work for you.

**Comment by TTcoinDeveloper** [comment]
Sure

**Comment by ianeinser** [comment]
update this in config/app.yml

tower: quay/io/openware/tower:2.2.8

**Comment by bzero** [comment]
tower is not published:
https://quay.io/organization/openware

**Comment by dpatsora** [comment]
Hi!

Tower image is public now.

Sincerely yours, 
OW team
